- hosts: myserver
  tasks:
  - name: Install docker.
    package:
      name: docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: Create a nginx container
    docker_container:
      name: nginx
      image: nginx
      state: started
      recreate: yes
      exposed_ports:
        - 80
